import {
  newArrCamera,
  newArrHeadphone,
  newArrLaptops,
  newArrSmartWatch,
  newArrTablets,
  bestSaleBlueIphone,
  bestSalePrinter,
  bestSaleSmartWatch,
  bestSaleSpeaker,
  bestSaleTablet,
  productOfTheYear,
  speOffBlueIphone,
  speOffLaptops,
  speOffTablet,
  spfBlueIphone,
  spfRedIphone,
  spfSpeaker,
  spfTablets,
  prodcut,
  samsungIpad,
  monitor,
  appipad,
  applap,
  asuaslap,
  game,
  iapdlap,
  ipadgreen,
} from '../../assets/allImg';

const paginationItems = [
  {
    _id: 1001,
    img: newArrCamera,
    productName: 'Cap for Boys',
    price: '35.00',
    color: 'Blank and White',
    badge: true,
    des: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.',
  },
  {
    _id: 1002,
    img: newArrHeadphone,
    productName: 'Tea Table',
    price: '180.00',
    color: 'Gray',
    badge: true,
    des: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.',
  },
  {
    _id: 1003,
    img: newArrLaptops,
    productName: 'Headphones',
    price: '25.00',
    color: 'Mixed',
    badge: true,
    des: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.',
  },
  {
    _id: 1004,
    img: monitor,
    productName: 'Sun glasses',
    price: '220.00',
    color: 'Black',
    badge: true,
    des: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.',
  },
  {
    _id: 1005,
    img: ipadgreen,
    productName: 'Flower Base',
    price: '35.00',
    color: 'Blank and White',
    badge: true,
    des: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.',
  },
  {
    _id: 1006,
    img: productOfTheYear,
    productName: 'New Backpack',
    price: '180.00',
    color: 'Gray',
    badge: false,
    des: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.',
  },
  {
    _id: 1007,
    img: monitor,
    productName: 'Household materials',
    price: '25.00',
    color: 'Mixed',
    badge: true,
    des: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.',
  },
  {
    _id: 1008,
    img: bestSaleTablet,
    productName: 'Travel Bag',
    price: '220.00',
    color: 'Black',
    badge: false,
    des: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.',
  },
  {
    _id: 1009,
    img: bestSaleSpeaker,
    productName: 'Round Table Clock',
    price: '44.00',
    color: 'Black',
    badge: true,
    des: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.',
  },
  {
    _id: 1010,
    img: bestSaleSmartWatch,
    productName: 'Smart Watch',
    price: '250.00',
    color: 'Black',
    badge: true,
    des: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.',
  },
  {
    _id: 1011,
    img: bestSalePrinter,
    productName: 'cloth Basket',
    price: '80.00',
    color: 'Mixed',
    badge: true,
    des: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.',
  },
  {
    _id: 1012,
    img: bestSaleBlueIphone,
    productName: 'Funny toys for babies',
    price: '60.00',
    color: 'Mixed',
    badge: false,
    des: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.',
  },
  {
    _id: 1013,
    img: newArrTablets,
    productName: 'Funny toys for babies',
    price: '60.00',
    color: 'Mixed',
    badge: false,
    des: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.',
  },

  {
    _id: 1014,
    img: newArrSmartWatch,
    productName: 'Smart Watch',
    price: '250.00',
    color: 'Black',
    badge: true,
    des: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.',
  },
  {
    _id: 1015,
    img: spfTablets,
    productName: 'Funny toys for babies',
    price: '60.00',
    color: 'Mixed',
    badge: false,
    des: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.',
  },
  {
    _id: 1016,
    img: spfSpeaker,
    productName: 'Smart Watch',
    price: '250.00',
    color: 'Black',
    badge: true,
    des: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.',
  },
  {
    _id: 1017,
    img: spfRedIphone,
    productName: 'Travel Bag',
    price: '220.00',
    color: 'Black',
    badge: false,
    des: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.',
  },
  {
    _id: 1018,
    img: spfBlueIphone,
    productName: 'Round Table Clock',
    price: '44.00',
    color: 'Black',
    badge: true,
    des: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.',
  },
  {
    _id: 1019,
    img: speOffTablet,
    productName: 'Smart Watch',
    price: '250.00',
    color: 'Black',
    badge: true,
    des: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.',
  },
  {
    _id: 1020,
    img: speOffLaptops,
    productName: 'cloth Basket',
    price: '80.00',
    color: 'Mixed',
    badge: true,
    des: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.',
  },
  {
    _id: 1021,
    img: speOffBlueIphone,
    productName: 'Headphones',
    price: '25.00',
    color: 'Mixed',
    badge: true,
    des: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.',
  },
  {
    _id: 1022,
    img: monitor,
    productName: 'Sun glasses',
    price: '220.00',
    color: 'Black',
    badge: true,
    des: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.',
  },
  {
    _id: 1023,
    img: samsungIpad,
    productName: 'Flower Base',
    price: '35.00',
    color: 'Blank and White',
    badge: true,
    des: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.',
  },
  {
    _id: 1024,
    img: prodcut,
    productName: 'Cap for Boys',
    price: '35.00',
    color: 'Blank and White',
    badge: true,
    des: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.',
  },
  {
    _id: 1025,
    img: ipadgreen,
    productName: 'Tea Table',
    price: '180.00',
    color: 'Gray',
    badge: true,
    des: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.',
  },
  {
    _id: 1026,
    img: iapdlap,
    productName: 'Headphones',
    price: '25.00',
    color: 'Mixed',
    badge: true,
    des: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.',
  },
  {
    _id: 1027,
    img: game,
    productName: 'Sun glasses',
    price: '220.00',
    color: 'Black',
    badge: true,
    des: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.',
  },
  {
    _id: 1028,
    img: asuaslap,
    productName: 'Flower Base',
    price: '35.00',
    color: 'Blank and White',
    badge: true,
    des: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.',
  },
  {
    _id: 1029,
    img: applap,
    productName: 'New Backpack',
    price: '180.00',
    color: 'Gray',
    badge: false,
    des: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.',
  },
  {
    _id: 1030,
    img: appipad,
    productName: 'Household materials',
    price: '25.00',
    color: 'Mixed',
    badge: true,
    des: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.',
  },
  {
    _id: 1031,
    img: monitor,
    productName: 'Travel Bag',
    price: '220.00',
    color: 'Black',
    badge: false,
    des: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.',
  },
  {
    _id: 1032,
    img: ipadgreen,
    productName: 'Round Table Clock',
    price: '44.00',
    color: 'Black',
    badge: true,
    des: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.',
  },
  {
    _id: 1033,
    img: iapdlap,
    productName: 'Smart Watch',
    price: '250.00',
    color: 'Black',
    badge: true,
    des: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.',
  },
  {
    _id: 1034,
    img: appipad,
    productName: 'cloth Basket',
    price: '80.00',
    color: 'Mixed',
    badge: true,
    des: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.',
  },
  {
    _id: 1035,
    img: samsungIpad,
    productName: 'Funny toys for babies',
    price: '60.00',
    color: 'Mixed',
    badge: false,
    des: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.',
  },
  {
    _id: 1036,
    img: prodcut,
    productName: 'Funny toys for babies',
    price: '60.00',
    color: 'Mixed',
    badge: false,
    des: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.',
  },
  {
    _id: 1037,
    img: spfSpeaker,
    productName: 'Funny toys for babies',
    price: '60.00',
    color: 'Mixed',
    badge: false,
    des: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.',
  },
  {
    _id: 1038,
    img: spfBlueIphone,
    productName: 'Smart Watch',
    price: '250.00',
    color: 'Black',
    badge: true,
    des: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.',
  },
  {
    _id: 1039,
    img: speOffLaptops,
    productName: 'Travel Bag',
    price: '220.00',
    color: 'Black',
    badge: false,
    des: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.',
  },
  {
    _id: 1040,
    img: productOfTheYear,
    productName: 'Round Table Clock',
    price: '44.00',
    color: 'Black',
    badge: true,
    des: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.',
  },
  {
    _id: 1041,
    img: bestSaleSpeaker,
    productName: 'Smart Watch',
    price: '250.00',
    color: 'Black',
    badge: true,
    des: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.',
  },
  {
    _id: 1042,
    img: bestSalePrinter,
    productName: 'cloth Basket',
    price: '80.00',
    color: 'Mixed',
    badge: true,
    des: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.',
  },
  {
    _id: 1043,
    img: newArrTablets,
    productName: 'Headphones',
    price: '25.00',
    color: 'Mixed',
    badge: true,
    des: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.',
  },
  {
    _id: 1044,
    img: newArrLaptops,
    productName: 'Sun glasses',
    price: '220.00',
    color: 'Black',
    badge: true,
    des: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.',
  },
  {
    _id: 1045,
    img: newArrCamera,
    productName: 'Flower Base',
    price: '35.00',
    color: 'Blank and White',
    badge: true,
    des: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.',
  },
  {
    _id: 1046,
    img: productOfTheYear,
    productName: 'Cap for Boys',
    price: '35.00',
    color: 'Blank and White',
    badge: true,
    des: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.',
  },
];
export default paginationItems;
